#define BATT_ADC_PIN GPIO_NUM_35
#define VBUS_ADC_PIN GPIO_NUM_36
#define I2C_SDA_PIN GPIO_NUM_21
#define I2C_SCL_PIN GPIO_NUM_22
#define RTC_INT_PIN GPIO_NUM_34
#define CHARGE_PIN GPIO_NUM_32
#define TP_PIN_PIN GPIO_NUM_33
#define IMU_INT_PIN GPIO_NUM_39
#define TP_PWR_PIN GPIO_NUM_25
#define LED_PIN GPIO_NUM_4

// EXT0 RTC_IO   pins: 0,2,4,12-15,25-27,32-39.
// EXT1 RTC_CNTL pins: 32-39
#define RTC_INT_SEL GPIO_SEL_34
#define CHARGE_SEL GPIO_SEL_32
#define TP_PIN_SEL GPIO_SEL_33
#define IMU_INT_SEL GPIO_SEL_39

#define MPU_ADDR 0x69

#ifdef DEBUG_PORT
#define DEBUG_MSG(...) DEBUG_PORT.printf(__VA_ARGS__)
#else
#define DEBUG_MSG(...)
#endif
